.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/dialogmelding/kafka/JacksonKafkaDeserializer.kt
src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingFromBehandler.kt
src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingFromBehandlerDTO.kt
src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingFromBehandlerTask.kt
src/main/kotlin/no/nav/syfo/domain/PartnerId.kt
src/test/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingFromBehandlerSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/DialogmeldingFromBehandlerGenerator.kt
src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt

Lagring av innkommende dialogmelding i databasen kommer i neste PR

Consumer for dialogmeldinger

---

README.md
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/behandlerdialog/api/BehandlerdialogApi.kt
src/main/kotlin/no/nav/syfo/behandlerdialog/api/MeldingTilBehandlerDTO.kt
src/main/kotlin/no/nav/syfo/behandlerdialog/api/domain/BehandlerdialogDTO.kt
src/test/kotlin/no/nav/syfo/behandlerdialog/api/BehandlerdialogApiSpek.kt
src/test/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingFromBehandlerSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/BehandlerdialogGenerator.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmeldingFromBehandlerGenerator.kt

Mye navngivning jeg vil ha innspill på her, se kommentarer.

Setup GET and POST endpoint for behandlerdialog

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/behandlerdialog/kafka/DialogmeldingBestillingDTO.kt
src/main/kotlin/no/nav/syfo/behandlerdialog/kafka/DialogmeldingBestillingProducer.kt
src/main/kotlin/no/nav/syfo/behandlerdialog/kafka/KafkaBehandlerDialogmeldingSerializer.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Noen TODOs her som må tas når vi har mer kode for å opprette utgående dialogmeldinger på plass.

Initial kafka producer setup with toggle

---

src/main/kotlin/no/nav/syfo/melding/database/MeldingQuery.kt
src/main/kotlin/no/nav/syfo/melding/kafka/KafkaDialogmeldingFraBehandlerConsumer.kt
src/main/kotlin/no/nav/syfo/melding/kafka/KafkaDialogmeldingFraBehandlerMetric.kt
src/main/kotlin/no/nav/syfo/melding/kafka/config/KafkaDialogmeldingFraBehandlerConfig.kt
src/main/kotlin/no/nav/syfo/melding/kafka/domain/KafkaDialogmeldingFraBehandlerDTO.kt
src/test/kotlin/no/nav/syfo/melding/kafka/KafkaDialogmeldingFraBehandlerConsumerSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmeldingFraBehandlerGenerator.kt

Filtrerer slik at vi bare lagrer innkommende dialogmeldinger som er svar på et melding som er sendt fra veileder.

Filter incoming

---

.nais/naiserator-dev.yaml

Turn on producer for bestillinger to isdialogmelding

---

src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cronjob/Cronjob.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobResult.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobRunner.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClient.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivMetric.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/AvsenderMottaker.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Bruker.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Dokument.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/DokumentInfo.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Dokumentvariant.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostResponse.kt
src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Sak.kt
src/main/kotlin/no/nav/syfo/client/leaderelection/LeaderPodClient.kt
src/main/kotlin/no/nav/syfo/client/leaderelection/LeaderPodDTO.kt
src/main/kotlin/no/nav/syfo/melding/cronjob/JournalforDialogmeldingCronjob.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Add prerequisites for journalforing: Cronjob module, leader election and Dokarkiv client. Not in use yet, and not tested.

Add journalforing prereqs

---

src/main/resources/db/migration/V1_8__add_column_journalpost_id.sql

Will be used to determine whether to journalføre an outgoing dialogmelding or not.

Add column for journalpost id

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Ble litt kluss det her da, men her er hvertfall endringen for å slå på topic og cronjob i prod dersom vi skal teste dialogmelding 👍🏼

Turn on kafka-producers in prod

---

src/main/kotlin/no/nav/syfo/melding/cronjob/MeldingFraBehandlerCronjob.kt
src/main/kotlin/no/nav/syfo/melding/database/domain/PMelding.kt
src/main/kotlin/no/nav/syfo/melding/domain/MeldingFraBehandler.kt
src/main/kotlin/no/nav/syfo/melding/kafka/PublishMeldingFraBehandlerService.kt
src/main/kotlin/no/nav/syfo/melding/kafka/domain/KafkaDialogmeldingFraBehandlerDTO.kt

Basert på hva som ble gjort i den andre PRen for ubesvart melding cronjob

Refactor meldingFraBehandler cronjob

---

src/main/kotlin/no/nav/syfo/melding/database/MeldingQuery.kt
src/test/kotlin/no/nav/syfo/melding/cronjob/UbesvartMeldingCronjobSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/MeldingGenerator.kt

Vi ønsker ikke å
- påminne på en påminnelse-melding
- påminne på en melding som fikk negativ apprec
Ekskluderer derfor disse fra resultatsettet i spørringen.

Exclude paminnelse-meldinger and avviste meldinger as ubesvarte meldinger

---

.github/workflows/kafka.yaml

Deploy ubesvartmelding topic to dev and prod

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Vi skal slå på påminnelser i prod for alle. Det gjenstår fortsatt noe arbeid, men pilotbrukerne har fått beskjed om dette, og resten av brukerne vil ikke se denne funksjonaliteten før om 2 uker uansett. Innen den tid vil ting være klart uansett 👍🏼🚀
Kommer en tilsvarende PR i `ispersonoppgave` også.

Turn on/remove toggle for cronjob ubesvart melding in prod

---

src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt
src/main/kotlin/no/nav/syfo/melding/cronjob/JournalforMeldingTilBehandlerCronjob.kt
src/main/kotlin/no/nav/syfo/melding/domain/MeldingTilBehandler.kt
src/test/kotlin/no/nav/syfo/melding/cronjob/JournalforMeldingTilBehandlerCronjobSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/JournalpostRequestGenerator.kt

Påminnelse skal fortsatt skyles for sluttbruker.

Show on mine saker

---

.nais/kafka/avvistmelding.yaml

Jeg hadde på reformatering i IntelliJ som endret denne til å ha whitespace, når den egentlig ikke skulle.

Remove whitespace from intelliJ-refactoring

---

.nais/alerts.yaml

This reverts commit f6781fcb5566430bdd8ba4a295852ff6a3615ae8.

Revert "test alert"

---

src/main/kotlin/no/nav/syfo/melding/api/MeldingResponseDTO.kt
src/main/kotlin/no/nav/syfo/melding/domain/MeldingFraBehandler.kt
src/main/kotlin/no/nav/syfo/melding/domain/MeldingTilBehandler.kt
src/test/kotlin/no/nav/syfo/melding/api/MeldingApiGetSpek.kt

Trenger disse i frontend for å vite om det er sendt retur på en gitt legeerklæring.

Add refs to MeldingDTO

---

src/main/kotlin/no/nav/syfo/melding/MeldingService.kt
src/main/kotlin/no/nav/syfo/melding/api/MeldingApi.kt
src/main/kotlin/no/nav/syfo/melding/api/ReturAvLegeerklaringRequestDTO.kt
src/main/kotlin/no/nav/syfo/melding/domain/MeldingTilBehandler.kt
src/test/kotlin/no/nav/syfo/melding/api/MeldingApiPostSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/ReturAvLegeerklaringGenerator.kt

Siden vi nå skal sende med et fritekstfelt for retur, så må dette på plass i backend også 😄

[IS-1540] Add fritekst field for retur av legeerklæring

---

src/main/kotlin/no/nav/syfo/melding/domain/MeldingTilBehandler.kt

Ref mandagsmøte så ønsker vi å vise retur på Min side.

[IS-1540] Include retur in godkjent innsyn on Min side

---

src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
src/main/resources/db/migration/V2_9__fix_timestamp.sql

Midlertidig fix til vi får orden på pale-2

Fix timestamp incoming legeerklaring

---

src/main/kotlin/no/nav/syfo/client/pdfgen/PdfGenClient.kt
src/test/kotlin/no/nav/syfo/melding/api/MeldingApiPostSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/PdfGenClientMock.kt

Venter på https://github.com/navikt/dialogmeldingpdfgen/pull/12/files ✅

[IS-1574] Generate pdf for melding fra nav

---

src/main/kotlin/no/nav/syfo/melding/api/MeldingResponseDTO.kt
src/main/kotlin/no/nav/syfo/melding/domain/MeldingFraBehandler.kt
src/main/kotlin/no/nav/syfo/melding/domain/MeldingTilBehandler.kt
src/main/kotlin/no/nav/syfo/melding/kafka/legeerklaring/LegeerklaringDTO.kt
src/test/kotlin/no/nav/syfo/melding/api/MeldingApiGetSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt

Slik at frontend kan vise egen tekst for vedlegg-lenke til legeerklæring

Add isFirstVedleggLegeerklaring flag to dto

---

.github/pull_request_template.md
build.gradle.kts

Oppdaterer noen dependencies, og sletter noen som ikke er i bruk.

Update dependencies (dependabot alerts)

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/api/ApiPlugins.kt
src/main/kotlin/no/nav/syfo/application/api/access/APIConsumerAccessService.kt
src/main/kotlin/no/nav/syfo/application/api/access/ForbiddenAccessSystemConsumer.kt
src/main/kotlin/no/nav/syfo/client/azuread/AzureEnvironment.kt
src/main/kotlin/no/nav/syfo/melding/MeldingService.kt
src/main/kotlin/no/nav/syfo/melding/api/MeldingSystemApi.kt
src/main/kotlin/no/nav/syfo/melding/database/MeldingQuery.kt
src/test/kotlin/no/nav/syfo/melding/api/MeldingSystemApiSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/JWTUtil.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

System-API for `padm2` til å sjekke om en melding med en gitt `msgId` er lagret i isbehandlerdialog.

IS-1683: Add system-api to check if melding with msgId exists

---

.nais/naiserator-prod.yaml
src/test/kotlin/no/nav/syfo/melding/cronjob/UbesvartMeldingCronjobSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Endret slik at en melding regnes som ubesvart når de har gått tre uker uten svar (tidligere to uker)

IS-1662: Three weeks frist for paminnelse

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/melding/kafka/dialogmelding/KafkaDialogmeldingFraBehandlerConsumer.kt
src/main/kotlin/no/nav/syfo/melding/kafka/dialogmelding/KafkaDialogmeldingFraBehandlerTask.kt
src/test/kotlin/no/nav/syfo/melding/kafka/KafkaDialogmeldingFraBehandlerConsumerSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Enabler melding til NAV i prod

Enable melding til nav

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/melding/kafka/dialogmelding/KafkaDialogmeldingFraBehandlerConsumer.kt
src/main/kotlin/no/nav/syfo/melding/kafka/dialogmelding/KafkaDialogmeldingFraBehandlerTask.kt
src/test/kotlin/no/nav/syfo/melding/kafka/KafkaDialogmeldingFraBehandlerConsumerSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

This reverts commit c61f7eb0b0b369549c684f11f18c51fd103ad91d.
Vi ser at mange av "melding til NAV" som nå blir lagret i Modia burde ha gått til Arena likevel.

Revert "Enable melding til nav (#133)"

---

src/main/kotlin/no/nav/syfo/melding/kafka/dialogmelding/KafkaDialogmeldingFraBehandlerConsumer.kt
src/main/kotlin/no/nav/syfo/melding/kafka/domain/KafkaDialogmeldingFraBehandlerDTO.kt
src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmeldingFraBehandlerGenerator.kt

Svar på møteinnkalling bør ikke telles som "no conversation" - de håndteres av isdialogmote.

IS-1673: Do not count svar moteinnkaling as no conversation

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/melding/kafka/dialogmelding/KafkaDialogmeldingFraBehandlerConsumer.kt
src/main/kotlin/no/nav/syfo/melding/kafka/dialogmelding/KafkaDialogmeldingFraBehandlerTask.kt
src/test/kotlin/no/nav/syfo/melding/kafka/KafkaDialogmeldingFraBehandlerConsumerSpek.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt

Enabler melding til NAV - nytt forsøk.

IS-1738: Enable melding til NAV in prod

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/client/ClientsEnvironment.kt
src/main/kotlin/no/nav/syfo/client/veiledertilgang/Tilgang.kt
src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt
src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClientMetric.kt
src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/MockHttpClient.kt
src/test/kotlin/no/nav/syfo/testhelper/mock/TilgangskontrollMock.kt

Endrer fra syfo-tilgangskontroll -> istilgangskontroll for tilgang til person-sjekk

IS-1689: Use istilgangskontroll

---

src/main/resources/db/migration/V3_1__delete_wrong_melding.sql

Sletter melding med tekst om feil bruker (https://jira.adeo.no/browse/FAGSYSTEM-302828)

IS-1762: Delete wrong melding

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/main/kotlin/no/nav/syfo/melding/cronjob/RepairLegeerklaringCronjob.kt

Engangs cronjob som skal fikse 149 pdf'er som ble feil på fredag 2023-11-17

IS-1826: Repair pdf for legeerklaring

---

src/main/kotlin/no/nav/syfo/melding/cronjob/RepairLegeerklaringCronjob.kt

Det ble et problem omtrent som Eirik antydet kunne skje. Så det gjenstår 6 legeerklæringer som må fikses (143 ble fikset av forrige kjøring).
Kommer ny PR som fjerner denne cronjob'en når denne kjøringen er ok.

IS-1826: Repair pdf for legeerklaring (again)

---

src/main/resources/db/migration/V3_2__delete_feilsendt.sql

[Jira-sak](https://jira.adeo.no/browse/FAGSYSTEM-309733)

IS-1930: Sletter to meldinger ifm feilsending

---

src/main/resources/db/migration/V3_3__delete_feilsendt_melding.sql

Se Jira-sak: https://jira.adeo.no/browse/FAGSYSTEM-305867

Delete feilsendt innkommende melding

---

src/main/resources/db/migration/V3_4__delete_feilsendt_melding.sql

Ref. https://jira.adeo.no/browse/FAGSYSTEM-313775
Sletter den feilsendte meldingen og oppfølgingsmeldingen til samme behandler som forklarer feilsendingen.

IS-1988: Sletter feilsendt melding

---

src/main/resources/db/migration/V3_5__delete_feilsendt_melding.sql

https://jira.adeo.no/browse/FAGSYSTEM-314005

IS-1992: Sletter feilsendt melding

---

.github/workflows/alerts.yaml
.github/workflows/kafka.yaml

Hva er nytt / hva har blitt fikset?

IS-1921: Upgrade deploy actions

---

src/main/resources/db/migration/V3_6__delete_meldinger.sql

Se https://jira.adeo.no/browse/FAGSYSTEM-327241 og https://jira.adeo.no/browse/FAGSYSTEM-327290

IS-2322: Sletter feilsendte dialogmeldinger

---

src/main/resources/db/migration/V3_7__delete_feilsendt_melding.sql

Se https://jira.adeo.no/browse/FAGSYSTEM-330033

IS-2373: Slett feilsendt melding

---

src/main/resources/db/migration/V3_8__delete_feilsendt_melding_and_svar.sql

Sletter feilsendt melding og tilhørende svar fra behandler

IS-2461: Slett feilsendt melding og svar

---

src/main/resources/db/migration/V4_00__delete_feilsendt_melding.sql

Sletter feilsendt melding: https://jira.adeo.no/browse/FAGSYSTEM-339585

IS-2548: Slett feilsendt melding

---

.github/dependabot.yaml
.nais/naiserator-dev.yaml
README.md
build.gradle.kts
gradle.properties
src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt

Sånn at dependabot finner avhengigheter og lagrer ukentige PRs på oppdateringer. Grupperer minor og patch-oppdatering i samme PR.

Fix dependabot

---

src/main/resources/db/migration/V4_01__delete_feilsendt_melding.sql

Se jirasak: https://jira.adeo.no/browse/FAGSYSTEM-346916

IS-2676: Delete feilsendt melding

---

src/main/resources/db/migration/V4_03__delete_feilsendt_melding.sql

Sletter feilsendt melding: FAGSYSTEM-353580

IS-2776: Slett feilsendt melding

---

src/main/kotlin/no/nav/syfo/melding/domain/MeldingTilBehandler.kt
src/main/kotlin/no/nav/syfo/melding/kafka/domain/DialogmeldingBestillingDTO.kt
src/test/kotlin/no/nav/syfo/melding/api/MeldingApiPostSpek.kt

Ref: https://github.com/navikt/isdialogmelding/pull/378

IS-2797: legge til kilde på dialogmeldingbestillinger

---

src/main/kotlin/no/nav/syfo/melding/kafka/dialogmelding/KafkaDialogmeldingFraBehandlerConsumer.kt

Kommer litt dårlige data har i dev (som gjør at pod'ene krasjer hyppig), så gjøre koden mer robust.

IS-3096: Handle invalid-uuid parentRef

---

src/main/resources/db/migration/V4_04__delete_feilsendt_melding.sql

Sletter feilsendt dialogmelding. Ref: https://jira.adeo.no/browse/FAGSYSTEM-371545

IS-3149: Slett feilsendt melding

---

src/main/resources/db/migration/V4_05__delete_feilsendt_melding.sql

Sletter svaret på en melding som ble slettet tidligere

IS.3209: Delete feilsendt melding

---

src/main/resources/db/migration/V4_06__delete_feilsendt_melding.sql

Sletter melding med innhold som handlet om annen pasient

IS.3219: Delete feilsendt melding

---

src/main/resources/db/migration/V4_07__delete_feilsendt_melding_and_svar.sql

Sletter feilsendt melding og tilhørende svar fra behandler

IS-3248: Delete feilsendt melding

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml

IS-3251: Oppgraderer til Postgres 17

---

src/main/resources/db/migration/V4_09__delete_feilsendt_melding.sql

IS-3320: Sletter feilsendt melding

---

src/main/resources/db/migration/V4_10__delete_feilsendt_melding.sql

https://jira.adeo.no/browse/FAGSYSTEM-386326

IS-3326: Slette feilsendt melding

---

src/main/kotlin/no/nav/syfo/App.kt

- Fikser feilende deploy. Feilen var at databasen ikke var initialisert da repository skulle bruke databasen til sin egen instantisering.

IS-Refactor-2: Fix database not initialized
